spring:
  h2:
    console:
      enabled: true # H2 ?? ?? ??
      path: /h2-console
  #DB Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: root
    password: dhehdgus12
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql : true
        format_sql: true
        use_sql_comments:  true # sql? ?? jpql ?????? ???? ??

